[project]
name = "alarm-discounts-bank"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcchapi>=1.1.2",
    "dotenv>=0.9.9",
    "pandas>=2.3.3",
    "selenium>=4.39.0",
    "webdriver-manager>=4.0.2",
]
